(cl:defpackage dynamixel_workbench_msgs-srv
  (:use )
  (:export
   "GETWORKBENCHPARAM"
   "<GETWORKBENCHPARAM-REQUEST>"
   "GETWORKBENCHPARAM-REQUEST"
   "<GETWORKBENCHPARAM-RESPONSE>"
   "GETWORKBENCHPARAM-RESPONSE"
   "SETDIRECTION"
   "<SETDIRECTION-REQUEST>"
   "SETDIRECTION-REQUEST"
   "<SETDIRECTION-RESPONSE>"
   "SETDIRECTION-RESPONSE"
   "SETPOSITION"
   "<SETPOSITION-REQUEST>"
   "SETPOSITION-REQUEST"
   "<SETPOSITION-RESPONSE>"
   "SETPOSITION-RESPONSE"
  ))

