set(_CATKIN_CURRENT_PACKAGE "dynamixel_workbench_controllers")
set(dynamixel_workbench_controllers_VERSION "0.1.3")
set(dynamixel_workbench_controllers_MAINTAINER "Pyo <pyo@robotis.com>")
set(dynamixel_workbench_controllers_PACKAGE_FORMAT "1")
set(dynamixel_workbench_controllers_BUILD_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_controllers_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_controllers_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_workbench_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_workbench_controllers_EXEC_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_controllers_RUN_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_controllers_TEST_DEPENDS )
set(dynamixel_workbench_controllers_DOC_DEPENDS )
set(dynamixel_workbench_controllers_DEPRECATED "")