set(_CATKIN_CURRENT_PACKAGE "dynamixel_workbench_single_manager")
set(dynamixel_workbench_single_manager_VERSION "0.1.3")
set(dynamixel_workbench_single_manager_MAINTAINER "Pyo <pyo@robotis.com>")
set(dynamixel_workbench_single_manager_PACKAGE_FORMAT "1")
set(dynamixel_workbench_single_manager_BUILD_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_single_manager_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_single_manager_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_workbench_single_manager_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_workbench_single_manager_EXEC_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_single_manager_RUN_DEPENDS "roscpp" "std_msgs" "dynamixel_workbench_msgs" "dynamixel_workbench_toolbox" "dynamixel_sdk")
set(dynamixel_workbench_single_manager_TEST_DEPENDS )
set(dynamixel_workbench_single_manager_DOC_DEPENDS )
set(dynamixel_workbench_single_manager_DEPRECATED "")