set(_CATKIN_CURRENT_PACKAGE "hark_sound_source_localization")
set(hark_sound_source_localization_VERSION "0.0.1")
set(hark_sound_source_localization_MAINTAINER "Sammy Pfeiffer <Sammy.Pfeiffer@student.uts.edu.au>")
set(hark_sound_source_localization_PACKAGE_FORMAT "1")
set(hark_sound_source_localization_BUILD_DEPENDS )
set(hark_sound_source_localization_BUILD_EXPORT_DEPENDS "harkfd" "hark-ros-hydro")
set(hark_sound_source_localization_BUILDTOOL_DEPENDS "catkin")
set(hark_sound_source_localization_BUILDTOOL_EXPORT_DEPENDS )
set(hark_sound_source_localization_EXEC_DEPENDS "harkfd" "hark-ros-hydro")
set(hark_sound_source_localization_RUN_DEPENDS "harkfd" "hark-ros-hydro")
set(hark_sound_source_localization_TEST_DEPENDS )
set(hark_sound_source_localization_DOC_DEPENDS )
set(hark_sound_source_localization_DEPRECATED "")