# Install script for directory: /home/cun/catkin_ws/src

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  
      if (NOT EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}")
        file(MAKE_DIRECTORY "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}")
      endif()
      if (NOT EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/.catkin")
        file(WRITE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/.catkin" "")
      endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/_setup_util.py")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE PROGRAM FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/_setup_util.py")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/env.sh")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE PROGRAM FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/env.sh")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/setup.bash")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE FILE FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/setup.bash")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/setup.sh")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE FILE FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/setup.sh")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/setup.zsh")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE FILE FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/setup.zsh")
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/local/.rosinstall")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/local" TYPE FILE FILES "/home/cun/catkin_ws/src/libfreenect/catkin_generated/installspace/.rosinstall")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/cun/catkin_ws/src/libfreenect/gtest/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/hark_sound_localization/hark_sound_source_localization/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/navigation/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/slam_gmapping/slam_gmapping/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench_msgs/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/DynamixelSDK/ros/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench_toolbox/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench_controllers/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench_single_manager/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/dynamixel-workbench/dynamixel_workbench_tutorials/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/hark_sound_localization/hark_msgs/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/oroca_ros_tutorial/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/depthimage_to_laserscan/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/darrsm/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/fake_localization/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/slam_gmapping/gmapping/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/map_server/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/amcl/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/robot_pose_ekf/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/voxel_grid/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/costmap_2d/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/nav_core/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/base_local_planner/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/carrot_planner/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/clear_costmap_recovery/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/dwa_local_planner/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/move_slow_and_clear/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/navfn/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/global_planner/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/rotate_recovery/cmake_install.cmake")
  include("/home/cun/catkin_ws/src/libfreenect/navigation/move_base/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/cun/catkin_ws/src/libfreenect/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
