set(_CATKIN_CURRENT_PACKAGE "dynamixel_workbench_msgs")
set(dynamixel_workbench_msgs_VERSION "0.1.3")
set(dynamixel_workbench_msgs_MAINTAINER "Pyo <pyo@robotis.com>")
set(dynamixel_workbench_msgs_PACKAGE_FORMAT "1")
set(dynamixel_workbench_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(dynamixel_workbench_msgs_BUILD_EXPORT_DEPENDS "message_generation" "std_msgs")
set(dynamixel_workbench_msgs_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_workbench_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_workbench_msgs_EXEC_DEPENDS "message_generation" "std_msgs")
set(dynamixel_workbench_msgs_RUN_DEPENDS "message_generation" "std_msgs")
set(dynamixel_workbench_msgs_TEST_DEPENDS )
set(dynamixel_workbench_msgs_DOC_DEPENDS )
set(dynamixel_workbench_msgs_DEPRECATED "")