// Generated by gencpp from file oroca_ros_tutorial/srvTutorial.msg
// DO NOT EDIT!


#ifndef OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIAL_H
#define OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIAL_H

#include <ros/service_traits.h>


#include <oroca_ros_tutorial/srvTutorialRequest.h>
#include <oroca_ros_tutorial/srvTutorialResponse.h>


namespace oroca_ros_tutorial
{

struct srvTutorial
{

typedef srvTutorialRequest Request;
typedef srvTutorialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvTutorial
} // namespace oroca_ros_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::oroca_ros_tutorial::srvTutorial > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::oroca_ros_tutorial::srvTutorial&) { return value(); }
};

template<>
struct DataType< ::oroca_ros_tutorial::srvTutorial > {
  static const char* value()
  {
    return "oroca_ros_tutorial/srvTutorial";
  }

  static const char* value(const ::oroca_ros_tutorial::srvTutorial&) { return value(); }
};


// service_traits::MD5Sum< ::oroca_ros_tutorial::srvTutorialRequest> should match 
// service_traits::MD5Sum< ::oroca_ros_tutorial::srvTutorial > 
template<>
struct MD5Sum< ::oroca_ros_tutorial::srvTutorialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::oroca_ros_tutorial::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorial::srvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::oroca_ros_tutorial::srvTutorialRequest> should match 
// service_traits::DataType< ::oroca_ros_tutorial::srvTutorial > 
template<>
struct DataType< ::oroca_ros_tutorial::srvTutorialRequest>
{
  static const char* value()
  {
    return DataType< ::oroca_ros_tutorial::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorial::srvTutorialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::oroca_ros_tutorial::srvTutorialResponse> should match 
// service_traits::MD5Sum< ::oroca_ros_tutorial::srvTutorial > 
template<>
struct MD5Sum< ::oroca_ros_tutorial::srvTutorialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::oroca_ros_tutorial::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorial::srvTutorialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::oroca_ros_tutorial::srvTutorialResponse> should match 
// service_traits::DataType< ::oroca_ros_tutorial::srvTutorial > 
template<>
struct DataType< ::oroca_ros_tutorial::srvTutorialResponse>
{
  static const char* value()
  {
    return DataType< ::oroca_ros_tutorial::srvTutorial >::value();
  }
  static const char* value(const ::oroca_ros_tutorial::srvTutorialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIAL_H
