// Generated by gencpp from file oroca_ros_tutorial/srvTutorialResponse.msg
// DO NOT EDIT!


#ifndef OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIALRESPONSE_H
#define OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace oroca_ros_tutorial
{
template <class ContainerAllocator>
struct srvTutorialResponse_
{
  typedef srvTutorialResponse_<ContainerAllocator> Type;

  srvTutorialResponse_()
    : result(0)  {
    }
  srvTutorialResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvTutorialResponse_

typedef ::oroca_ros_tutorial::srvTutorialResponse_<std::allocator<void> > srvTutorialResponse;

typedef boost::shared_ptr< ::oroca_ros_tutorial::srvTutorialResponse > srvTutorialResponsePtr;
typedef boost::shared_ptr< ::oroca_ros_tutorial::srvTutorialResponse const> srvTutorialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace oroca_ros_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'oroca_ros_tutorial': ['/home/cun/catkin_ws/src/oroca_ros_tutorial/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "oroca_ros_tutorial/srvTutorialResponse";
  }

  static const char* value(const ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n\
";
  }

  static const char* value(const ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvTutorialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::oroca_ros_tutorial::srvTutorialResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OROCA_ROS_TUTORIAL_MESSAGE_SRVTUTORIALRESPONSE_H
