set(_CATKIN_CURRENT_PACKAGE "dynamixel_workbench_toolbox")
set(dynamixel_workbench_toolbox_VERSION "0.1.3")
set(dynamixel_workbench_toolbox_MAINTAINER "Pyo <pyo@robotis.com>")
set(dynamixel_workbench_toolbox_PACKAGE_FORMAT "1")
set(dynamixel_workbench_toolbox_BUILD_DEPENDS "roscpp" "roslib" "std_msgs")
set(dynamixel_workbench_toolbox_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "std_msgs")
set(dynamixel_workbench_toolbox_BUILDTOOL_DEPENDS "catkin")
set(dynamixel_workbench_toolbox_BUILDTOOL_EXPORT_DEPENDS )
set(dynamixel_workbench_toolbox_EXEC_DEPENDS "roscpp" "roslib" "std_msgs")
set(dynamixel_workbench_toolbox_RUN_DEPENDS "roscpp" "roslib" "std_msgs")
set(dynamixel_workbench_toolbox_TEST_DEPENDS )
set(dynamixel_workbench_toolbox_DOC_DEPENDS )
set(dynamixel_workbench_toolbox_DEPRECATED "")