(cl:in-package dynamixel_workbench_msgs-msg)
(cl:export '(MODEL_NUMBER-VAL
          MODEL_NUMBER
          VERSION_OF_FIRMWARE-VAL
          VERSION_OF_FIRMWARE
          ID-VAL
          ID
          BAUD_RATE-VAL
          BAUD_RATE
          RETURN_DELAY_TIME-VAL
          RETURN_DELAY_TIME
          CW_ANGLE_LIMIT-VAL
          CW_ANGLE_LIMIT
          CCW_ANGLE_LIMIT-VAL
          CCW_ANGLE_LIMIT
          CONTROL_MODE-VAL
          CONTROL_MODE
          LIMIT_TEMPERATURE-VAL
          LIMIT_TEMPERATURE
          DOWN_LIMIT_VOLTAGE-VAL
          DOWN_LIMIT_VOLTAGE
          UP_LIMIT_VOLTAGE-VAL
          UP_LIMIT_VOLTAGE
          MAX_TORQUE-VAL
          MAX_TORQUE
          RETURN_LEVEL-VAL
          RETURN_LEVEL
          ALARM_SHUTDOWN-VAL
          ALARM_SHUTDOWN
          TORQUE_ENABLE-VAL
          TORQUE_ENABLE
          LED-VAL
          LED
          D_GAIN-VAL
          D_GAIN
          I_GAIN-VAL
          I_GAIN
          P_GAIN-VAL
          P_GAIN
          GOAL_POSITION-VAL
          GOAL_POSITION
          GOAL_VELOCITY-VAL
          GOAL_VELOCITY
          GOAL_TORQUE-VAL
          GOAL_TORQUE
          PRESENT_POSITION-VAL
          PRESENT_POSITION
          PRESENT_VELOCITY-VAL
          PRESENT_VELOCITY
          PRESENT_LOAD-VAL
          PRESENT_LOAD
          PRESENT_VOLTAGE-VAL
          PRESENT_VOLTAGE
          PRESENT_TEMPERATURE-VAL
          PRESENT_TEMPERATURE
          REGISTERED_INSTRUCTION-VAL
          REGISTERED_INSTRUCTION
          MOVING-VAL
          MOVING
          HARDWARE_ERROR_STATUS-VAL
          HARDWARE_ERROR_STATUS
          PUNCH-VAL
          PUNCH
))